// Package frontend provides helpers for serving Vite-built frontend assets
// embedded in the Go binary via go:embed, plus a development proxy for hot-module
// reload during development.
package frontend

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// Manager handles serving frontend assets in both dev and production modes.
type Manager struct {
	mu      sync.RWMutex
	mode    string // "dev" | "prod"
	devURL  string // Vite dev server URL
	pubFS   fs.FS  // embedded production assets (nil in dev)
	manifest *viteMani
}

// New creates a frontend Manager.
//   - In dev mode, requests are proxied to the Vite dev server.
//   - In production mode, assets are served from the embedded pubFS.
func New(mode string, opts ...Option) *Manager {
	m := &Manager{mode: mode, devURL: "http://localhost:5173"}
	for _, o := range opts {
		o(m)
	}
	return m
}

// Option configures the Manager.
type Option func(*Manager)

// WithDevURL sets the Vite dev server URL (default: http://localhost:5173).
func WithDevURL(u string) Option {
	return func(m *Manager) { m.devURL = u }
}

// WithFS sets the embedded fs.FS for production assets.
// Typically this is the go:embed public/build directory.
func WithFS(fsys fs.FS) Option {
	return func(m *Manager) { m.pubFS = fsys }
}

// Handler returns an http.Handler that serves frontend assets.
// In dev mode it proxies to Vite; in prod it serves from the embedded FS.
func (m *Manager) Handler() http.Handler {
	if m.mode == "dev" {
		return m.devProxy()
	}
	return m.prodHandler()
}

// ViteTag returns the HTML <script> and <link> tags for the given entry point.
// In dev mode it points to Vite's dev server; in prod it uses the manifest.
//
//	{{.Frontend.ViteTag "resources/ts/app.ts"}}
func (m *Manager) ViteTag(entry string) string {
	if m.mode == "dev" {
		return fmt.Sprintf(
			`<script type="module" src="%s/%s"></script>`,
			strings.TrimRight(m.devURL, "/"), entry,
		)
	}

	m.mu.RLock()
	mani := m.manifest
	m.mu.RUnlock()

	if mani == nil {
		return "<!-- vite manifest not loaded -->"
	}

	chunk, ok := mani.Entries[entry]
	if !ok {
		return fmt.Sprintf("<!-- vite: entry %q not found in manifest -->", entry)
	}

	var tags strings.Builder
	// CSS
	for _, css := range chunk.CSS {
		tags.WriteString(fmt.Sprintf(`<link rel="stylesheet" href="/%s">`, css))
	}
	// JS
	tags.WriteString(fmt.Sprintf(`<script type="module" src="/%s"></script>`, chunk.File))
	return tags.String()
}

// LoadManifest parses the Vite manifest.json from the given path.
// Call this during app startup in production.
func (m *Manager) LoadManifest(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("frontend: load manifest %q: %w", path, err)
	}
	var raw map[string]struct {
		File    string   `json:"file"`
		CSS     []string `json:"css"`
		IsEntry bool     `json:"isEntry"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("frontend: parse manifest: %w", err)
	}
	mani := &viteMani{Entries: make(map[string]*viteChunk)}
	for src, chunk := range raw {
		mani.Entries[src] = &viteChunk{File: chunk.File, CSS: chunk.CSS}
	}
	m.mu.Lock()
	m.manifest = mani
	m.mu.Unlock()
	return nil
}

// ─────────────────────────── Dev proxy ───────────────────────────

func (m *Manager) devProxy() http.Handler {
	target, _ := url.Parse(m.devURL)
	proxy := httputil.NewSingleHostReverseProxy(target)
	return proxy
}

// ─────────────────────────── Prod handler ────────────────────────

func (m *Manager) prodHandler() http.Handler {
	if m.pubFS == nil {
		return http.NotFoundHandler()
	}
	return http.FileServer(http.FS(m.pubFS))
}

// ─────────────────────────── TS type generator ───────────────────

// GenerateTypes generates TypeScript type declarations for Go structs
// annotated with `json` tags and writes the output to a .ts file.
// This is a lightweight, reflection-free source code generator.
//
//	frontend.GenerateTypes("app/models", "resources/ts/types.generated.ts")
func GenerateTypes(srcDir, outFile string) error {
	structs, err := parseGoStructs(srcDir)
	if err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("// AUTO-GENERATED by oni — do not edit manually\n\n")
	for _, s := range structs {
		sb.WriteString(s.toTS())
		sb.WriteString("\n")
	}

	if err := os.MkdirAll(filepath.Dir(outFile), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outFile, []byte(sb.String()), 0o644)
}

// ─────────────────────────── Vite manifest types ─────────────────

type viteMani struct {
	Entries map[string]*viteChunk
}

type viteChunk struct {
	File string
	CSS  []string
}

// ─────────────────────────── Simple struct parser ─────────────────

type tsStruct struct {
	Name   string
	Fields []tsField
}

type tsField struct {
	Name     string
	TSType   string
	Optional bool
}

func (s *tsStruct) toTS() string {
	var sb strings.Builder
	sb.WriteString("export interface " + s.Name + " {\n")
	for _, f := range s.Fields {
		opt := ""
		if f.Optional {
			opt = "?"
		}
		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", f.Name, opt, f.TSType))
	}
	sb.WriteString("}\n")
	return sb.String()
}

// parseGoStructs is a minimal struct scanner that reads *.go files
// and emits TS interfaces for exported structs with json tags.
func parseGoStructs(dir string) ([]*tsStruct, error) {
	var structs []*tsStruct
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		structs = append(structs, extractStructs(string(data))...)
	}
	return structs, nil
}

// extractStructs does a naïve line-by-line parse to find structs and json tags.
func extractStructs(src string) []*tsStruct {
	var result []*tsStruct
	lines := strings.Split(src, "\n")
	var cur *tsStruct

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if cur == nil {
			if strings.HasPrefix(trimmed, "type ") && strings.Contains(trimmed, " struct {") {
				parts := strings.Fields(trimmed)
				if len(parts) >= 3 {
					cur = &tsStruct{Name: parts[1]}
				}
			}
			continue
		}

		if trimmed == "}" {
			if len(cur.Fields) > 0 {
				result = append(result, cur)
			}
			cur = nil
			continue
		}

		// Parse fields with json tags
		if jsonTag := extractJSONName(trimmed); jsonTag != "" && jsonTag != "-" {
			tsType := goTypeToTS(trimmed)
			optional := strings.Contains(jsonTag, "omitempty")
			name := strings.ReplaceAll(jsonTag, ",omitempty", "")
			cur.Fields = append(cur.Fields, tsField{
				Name:     name,
				TSType:   tsType,
				Optional: optional,
			})
		}
	}
	return result
}

func extractJSONName(field string) string {
	start := strings.Index(field, `json:"`)
	if start < 0 {
		return ""
	}
	rest := field[start+6:]
	end := strings.Index(rest, `"`)
	if end < 0 {
		return ""
	}
	return rest[:end]
}

func goTypeToTS(field string) string {
	parts := strings.Fields(field)
	if len(parts) < 2 {
		return "unknown"
	}
	goType := parts[1]
	// Strip pointer
	goType = strings.TrimPrefix(goType, "*")

	switch goType {
	case "string":
		return "string"
	case "bool":
		return "boolean"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "number"
	case "time.Time":
		return "string" // ISO 8601
	case "json.RawMessage":
		return "unknown"
	}
	if strings.HasPrefix(goType, "[]") {
		inner := goTypeToTS(strings.TrimPrefix(goType, "[]") + " x")
		return inner + "[]"
	}
	if strings.HasPrefix(goType, "map[") {
		return "Record<string, unknown>"
	}
	return goType // assume interface name
}
